### ISSUE TITLE
不是pluginRepositorie，而是pluginRepository

### ISSUE THREAD

**Issue by zwmyxzs** [zongwei007/drone-maven-setting#3]
Unrecognised tag: 'pluginRepositorie' (position: START_TAG seen ...<pluginRepositories><pluginRepositorie>... @1:405)  @ /drone/src/service/kcc/settings.xml, line 1, column 405

**Comment by zongwei007** [comment]
已修复并发布。见 4f787785e80f24021add01a336867accda4c7c0f
